### ISSUE TITLE
getPriorList() features

### ISSUE THREAD

**Issue by mitchell-thomann** [Boehringer-Ingelheim/BayesianMCPMod#6]
Potential features:

- "Nc" argument to specify the number of prior components
- is it possible to allow informative priors for non-control doses?

**Comment by sebastianbossert** [comment]
Since there are various ways how a prior can be constructed (e.g. not only MAP based but also via other approaches) we decided to have this function for the first version only included in the vignette, but not as a main function of the package. In doing so people can in principle also create and use informative priors for all dose groups.
